### ISSUE TITLE
Import Error in python debugger

### ISSUE THREAD

**Issue by gvoysey** [nclack/whisk#37]
I've written a really quick script to mess around with measurements files post-hoc, in python.   I'm using a fork of this repo, but it's even with `master` and only has a few additions in it.

MWE: 
```
""" load_measurements.py"""
import sys
from traj import MeasurementsTable

def main():
    filepath = sys.argv[1] # this will be "C:/somefile.measurements"
    table = MeasurementsTable(filepath)
    print(len(table))

if __name__ == "__main__":
    sys.exit(main())
```

When i run this from a command prompt, I get: 
```
(root) C:\Users\VOYSEYG\Projects\whisk\python>python load_measurements.py "C:\Users\VOYSEYG\Dropbox\Whisker Tracking\test videos\synkenesis\YDXJ0106\YDXJ0106-left.measurements"
94456
```
which seems sensible. 

If i put in a breakpoint and try to step through this function, i get a crash : 

```
Connected to pydev debugger (build 171.4249.47)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.2\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.1.2\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/VOYSEYG/Projects/whisk/python/load_measurements.py", line 21, in <module>
    from traj import MeasurementsTable
  File "C:/Users/VOYSEYG/Projects/whisk/python\traj.py", line 17, in <module>
    from trace import cWhisker_Seg
ImportError: cannot import name cWhisker_Seg

Process finished with exit code 1
```

I'm confused why this is.  Any ideas?  `cWhisker_Seg` is a cTypes `Structure`, so perhaps there's some compilation step i've missed?

System: 
windows 10
python: `Python 2.7.13 :: Continuum Analytics, Inc.`
pip freeze: 
```
backports.shutil-get-terminal-size==1.0.0
cffi==1.9.1
colorama==0.3.9
conda==4.3.21
cryptography==1.7.1
cycler==0.10.0
Cython==0.25.2
decorator==4.0.11
docopt==0.6.2
enum34==1.1.6
functools32==3.2.3.post2
idna==2.2
ipaddress==1.0.18
ipython==5.3.0
ipython-genutils==0.2.0
matplotlib==2.0.2
menuinst==1.4.4
numpy==1.12.1
pandas==0.20.1
path.py==10.3.1
pathlib2==2.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
Pygments==2.2.0
pyOpenSSL==16.2.0
pyparsing==2.1.4
python-dateutil==2.6.0
pytz==2017.2
pywin32==220
requests==2.12.4
scandir==1.5
scipy==0.19.0
simplegeneric==0.8.1
six==1.10.0
subprocess32==3.2.7
traitlets==4.3.2
wcwidth==0.1.7
win-unicode-console==0.5
```

**Comment by nclack** [comment]
Is that the wrong trace module is being loaded?

One way to check is to `import trace` in a python console and `dir(trace)` to make sure the contents look right.

**Comment by gvoysey** [comment]
I don't think so.   I put a quick `print(__file__)` in `trace.py` before the offending import and it was the proper location.  

I think pycharm is getting deeply confused, but i'm not sure how come.
